### ISSUE TITLE
PG::UndefinedColumn: ERROR column "authenticator" does not exist

### ISSUE THREAD

**Issue by jandudulski** [rbCAS/CASino#87]
I've just installed `CASino` gem, generated migrations and run them with error:

```bash
PG::UndefinedColumn: ERROR:  column "authenticator" does not exist
: CREATE UNIQUE INDEX  "index_casino_users_on_authenticator_and_username" ON "casino_users"  ("authenticator", "username")
/home/yanoo/Code/project/db/migrate/20150115141937_rename_base_models.casino.rb:62:in `up'
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "authenticator" does not exist
: CREATE UNIQUE INDEX  "index_casino_users_on_authenticator_and_username" ON "casino_users"  ("authenticator", "username")
/home/yanoo/Code/project/db/migrate/20150115141937_rename_base_models.casino.rb:62:in `up'
PG::UndefinedColumn: ERROR:  column "authenticator" does not exist
/home/yanoo/Code/project/db/migrate/20150115141937_rename_base_models.casino.rb:62:in `up'
```

**Comment by jandudulski** [comment]
Ah, I had already users table so it wasn't created in the `CreateCoreSchema` migration.

It would be better to generate final migration instead of multiple renaming, don't you think?
